name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Zip the Binary
        run: |
          zip azure-keyvault-unlock-luks-${{ github.ref_name }}.zip target/x86_64-unknown-linux-gnu/release/luks_unlocker  # Use the correct path and binary name

      - name: Create SHA256 Checksum
        run: |
          sha256sum azure-keyvault-unlock-luks-${{ github.ref_name }}.zip > azure-keyvault-unlock-luks-${{ github.ref_name }}.zip.sha256  # Use the correct naming convention

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Release of version ${{ github.ref_name }}.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: azure-keyvault-unlock-luks-${{ github.ref_name }}.zip
          asset_name: azure-keyvault-unlock-luks-${{ github.ref_name }}.zip
          asset_content_type: application/zip

      - name: Upload SHA256 Checksum
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: azure-keyvault-unlock-luks-${{ github.ref_name }}.zip.sha256
          asset_name: azure-keyvault-unlock-luks-${{ github.ref_name }}.zip.sha256
          asset_content_type: text/plain
